#ifndef _EXTERN_FUNCTIONS_H_
#define _EXTERN_FUNCTIONS_H_

#include <stdlib.h>
#include <string.h>

#include "api.h"

MELD_DECLARE_FUNCTION1(to_float);
MELD_DECLARE_FUNCTION1(float_abs);
MELD_DECLARE_FUNCTION2(print_float);
MELD_DECLARE_FUNCTION1(nodeID);
MELD_DECLARE_FUNCTION2(print_int);
MELD_DECLARE_FUNCTION0(list_node_new);
MELD_DECLARE_FUNCTION1(list_size);
MELD_DECLARE_FUNCTION2(list_push_tail_node);
MELD_DECLARE_FUNCTION2(list_push_head_node);
MELD_DECLARE_FUNCTION1(generate_random);
MELD_DECLARE_FUNCTION0(empty_set);
MELD_DECLARE_FUNCTION2(set_insert_int);

#ifdef BELIEF_PROPAGATION
MELD_DECLARE_FUNCTION1(calculateListSum);
MELD_DECLARE_FUNCTION2(sumLists);
MELD_DECLARE_FUNCTION2(minusLists);
MELD_DECLARE_FUNCTION1(normalizeList);
MELD_DECLARE_FUNCTION1(convolve);
MELD_DECLARE_FUNCTION2(damp);
#endif

#endif
