
#ifndef NODE_HPP
#define NODE_HPP

#include <list>
#include <map>
#include <ostream>
#include <vector>
#include <utility>
#include <tr1/unordered_map>

#include "vm/tuple.hpp"
#include "vm/predicate.hpp"
#include "db/tuple.hpp"
#include "db/tuple_aggregate.hpp"
#include "mem/allocator.hpp"
#include "db/trie.hpp"
#include "vm/defs.hpp"
#include "vm/match.hpp"
#include "utils/atomic.hpp"
#include "db/edge_set.hpp"

namespace sched { class base; class mpi_handler; }
namespace process { class process; class machine; }

namespace db {

class node
{
public:
   
   typedef vm::node_val node_id;
   
   typedef trie::delete_info delete_info;
   
private:
   
	node_id id;
   node_id translation;
	
   typedef std::map<vm::predicate_id, tuple_trie*,
               std::less<vm::predicate_id>,
               mem::allocator<std::pair<const vm::predicate_id,
                                 tuple_trie*> > > simple_tuple_map;
                                 
   typedef std::map<vm::predicate_id, tuple_aggregate*,
               std::less<vm::predicate_id>,
               mem::allocator<std::pair<const vm::predicate_id,
                                 tuple_aggregate*> > > aggregate_map;
	
	// tuple database
   simple_tuple_map tuples;
   
   // sets of tuple aggregates
   aggregate_map aggs;
   
   // counters with numbers of tuples to process
   std::vector< utils::atomic<int> > to_proc;
   // counters with numbers of tuples generated by the node itself
   std::vector<int> auto_generated;
   
   typedef std::tr1::unordered_map<vm::predicate_id,
                           edge_set,
                           std::tr1::hash<vm::predicate_id>,
                           std::equal_to<vm::predicate_id>,
                           mem::allocator<std::pair<const vm::predicate_id, edge_set> > >
                  edge_map; 
   
   edge_map edge_info;
   
   tuple_trie* get_storage(const vm::predicate*);
   
   friend class sched::base;
   friend class process::process;
   friend class process::machine;
   friend class sched::mpi_handler;
   
   inline void new_auto_tuple(const simple_tuple *stpl)
   {
      more_to_process(stpl->get_predicate_id());
      auto_generated[stpl->get_predicate_id()]++;
   }
   
   inline bool no_more_to_process(const vm::predicate_id id) { return to_proc[id] == 0; }
   inline void more_to_process(const vm::predicate_id id) { assert(to_proc[id] >= 0); to_proc[id]++; }
   inline void less_to_process(const vm::predicate_id id) { assert(to_proc[id] >= 1); to_proc[id]--; }
	
public:
   
   inline node_id get_id(void) const { return id; }
   inline node_id get_translated_id(void) const { return translation; }
   
   bool add_tuple(vm::tuple*, vm::ref_count);
   delete_info delete_tuple(vm::tuple *, vm::ref_count);
   
   db::agg_configuration* add_agg_tuple(vm::tuple*, const vm::ref_count);
   void remove_agg_tuple(vm::tuple*, const vm::ref_count);
   simple_tuple_list end_iteration(void);
   
   const edge_set& get_edge_set(const vm::predicate_id id) const {
      assert(edge_info.find(id) != edge_info.end());
      return edge_info.find(id)->second;
   }
   
   void delete_by_first_int_arg(const vm::predicate*, const vm::int_val);
   void delete_all(const vm::predicate*);
   
   virtual void assert_end(void) const;
   virtual void assert_end_iteration(void) const {}
   void init(void);
   
   void match_predicate(const vm::predicate_id, tuple_vector&) const;
   void match_predicate(const vm::predicate_id, const vm::match&, tuple_vector&) const;
   
   size_t count_total(const vm::predicate_id) const;
   
   void print(std::ostream&) const;
   void dump(std::ostream&) const;
   
   explicit node(const node_id, const node_id);
   
   virtual ~node(void);
};

std::ostream& operator<<(std::ostream&, const node&);

}

#endif

